Repository sandialabs/Albany, pull requests merged in 2020-07, with the labels that each got.

#607 LandIce: refactoring of NullSpaceUtility
  src/Albany_NullSpaceUtils.cpp
  src/Albany_NullSpaceUtils.hpp
  src/LandIce/interface_with_mpas/Interface.cpp
  src/LandIce/problems/LandIce_Enthalpy.cpp
  src/LandIce/problems/LandIce_Hydrology.cpp
  src/LandIce/problems/LandIce_SchoofFit.cpp
  src/LandIce/problems/LandIce_Stokes.cpp
  src/LandIce/problems/LandIce_StokesFO.cpp
  src/LandIce/problems/LandIce_StokesFOBase.cpp
  src/LandIce/problems/LandIce_StokesFOBase.hpp
  src/LandIce/problems/LandIce_StokesFOThermoCoupled.cpp
  src/LandIce/problems/LandIce_StokesL1L2.cpp
  src/disc/stk/Albany_STKDiscretization.cpp
  src/problems/Albany_AbstractProblem.cpp
  src/problems/Albany_HeatProblem.cpp
  src/problems/Albany_PopulateMesh.cpp
  src/problems/Albany_ThermalProblem.cpp
  tests/small/LandIce/FO_AIS/input_FROSch.yaml
  tests/small/LandIce/FO_GIS/input_fo_gis_unstructT_FROSch.yaml
  tests/small/LandIce/FO_Test/input_fo_confinedShelf_depthIntBCT.yaml
Labels: enhancement, infrastructure

#612 GPU build failures on ride
  src/Albany_KokkosTypes.hpp
  src/Albany_TpetraTypes.hpp
Labels: bugfix

#600 Enthalpy Kokkos Refactor (Volume Evaluators)
  src/LandIce/evaluators/LandIce_Dissipation.hpp
  src/LandIce/evaluators/LandIce_Dissipation_Def.hpp
  src/LandIce/evaluators/LandIce_EnthalpyResid.hpp
  src/LandIce/evaluators/LandIce_EnthalpyResid_Def.hpp
  src/LandIce/evaluators/LandIce_HydrostaticPressure.hpp
  src/LandIce/evaluators/LandIce_HydrostaticPressure_Def.hpp
  src/LandIce/evaluators/LandIce_LiquidWaterFraction.hpp
  src/LandIce/evaluators/LandIce_LiquidWaterFraction_Def.hpp
  src/LandIce/evaluators/LandIce_PressureMeltingEnthalpy.hpp
  src/LandIce/evaluators/LandIce_PressureMeltingEnthalpy_Def.hpp
  src/LandIce/evaluators/LandIce_Temperature.hpp
  src/LandIce/evaluators/LandIce_Temperature_Def.hpp
  src/evaluators/interpolation/PHAL_NodesToCellInterpolation.hpp
  src/evaluators/interpolation/PHAL_NodesToCellInterpolation_Def.hpp
  src/utility/Albany_KokkosUtils.hpp
Labels: Kokkos, LandIce
