Repository sandialabs/Albany, pull requests merged in 2021-07, with the labels that each got.

#690 Update matrix manipulation utilities.
  src/Albany_Application.cpp
  src/responses/Albany_SolutionResponseFunction.cpp
  src/utility/Albany_EpetraThyraUtils.cpp
  src/utility/Albany_ThyraCrsMatrixFactory.cpp
  src/utility/Albany_ThyraUtils.cpp
  src/utility/Albany_ThyraUtils.hpp
  src/utility/Albany_TpetraThyraUtils.cpp
  src/utility/Albany_TpetraThyraUtils.hpp
Labels: Trilinos

#716 Add temporary throw when using Belos + Ifpack2/Amesos2
  src/Albany_SolverFactory.cpp
Labels: bug

#726 Fix PyAlbany stackedTimers when more than 1 problem is used
  PyAlbany/src/Albany_Interface.cpp
  PyAlbany/tests/small/SteadyHeat/steadyHeat.py
  PyAlbany/tests/small/SteadyHeat/steadyHeat_stateMap.py
Labels: PyAlbany
