Repository sandialabs/Albany, pull requests merged in 2021-08, with the labels that each got.

#728 Fix in the creation of Tpetra FECrsMatrix objects
  src/utility/Albany_ThyraCrsMatrixFactory.cpp
Labels: Trilinos, bugfix

#725 Sideset Dynamic Sizing
  src/Albany_Application.cpp
  src/Albany_Application.hpp
  src/LandIce/problems/LandIce_Enthalpy.cpp
  src/LandIce/problems/LandIce_LaplacianSampling.cpp
  src/LandIce/problems/LandIce_StokesFOBase.cpp
  src/disc/Albany_MeshSpecs.hpp
  src/disc/stk/Albany_ExtrudedSTKMeshStruct.cpp
  src/disc/stk/Albany_GenericSTKMeshStruct.cpp
  src/disc/stk/Albany_IossSTKMeshStruct.cpp
  src/disc/stk/Albany_STKDiscretization.cpp
  src/disc/stk/Albany_SideSetSTKMeshStruct.cpp
  src/disc/stk/Albany_SideSetSTKMeshStruct.hpp
  src/problems/Albany_Layouts.cpp
  src/problems/Albany_Layouts.hpp
  src/problems/Albany_PopulateMesh.cpp
  src/problems/Albany_SideLaplacianProblem.cpp
  src/responses/Albany_FieldManagerScalarResponseFunction.cpp
  tests/unit/disc/UnitTest_BlockedDOFManager.cpp
Labels: enhancement

#733 Fix the base timer of PyAlbany
  PyAlbany/src/Albany_Interface.cpp
  doc/LandIce/PyAlbany/Cori/Albany_Intel.sh
  doc/LandIce/PyAlbany/Cori/Trilinos_Intel.sh
  doc/LandIce/PyAlbany/Cori/conda.sh
  doc/LandIce/PyAlbany/Cori/module.sh
Labels: PyAlbany
