Repository sandialabs/Albany, pull requests merged in 2023-02, with the labels that each got.

#908 Handle special link options when creating albany export file
  cmake/CreateExportAlbany
Labels: bugfix

#900 Remove SFAD4 and SFAD8 builds
  doc/dashboards/blake.sandia.gov/ctest_nightly_albany-sfad_tmp.cmake
  doc/dashboards/blake.sandia.gov/do-cmake-albany-serial-sfad12
  doc/dashboards/blake.sandia.gov/do-cmake-albany-sfad
  doc/dashboards/blake.sandia.gov/nightly_cron_script_albany_blake_serial_sfad.sh
  doc/dashboards/blake.sandia.gov/run_intel.batch
  doc/dashboards/weaver.sandia.gov/ctest_nightly_albanySFAD_tmp.cmake
  doc/dashboards/weaver.sandia.gov/do-cmake-albanySFAD
  doc/dashboards/weaver.sandia.gov/nightly_cron_script_albany_weaver_sfad.sh
  doc/dashboards/weaver.sandia.gov/run_all_lsf.sh
Labels: LandIce, performance, Testing

#912 Fix fad offsets when dealing with column-coupled equations
  src/evaluators/response/PHAL_ResponseSquaredL2DifferenceSide_Def.hpp
  src/evaluators/scatter/PHAL_SeparableScatterScalarResponse.hpp
  src/evaluators/scatter/PHAL_SeparableScatterScalarResponse_Def.hpp
  src/landIce/evaluators/LandIce_Gather2DField.hpp
  src/landIce/evaluators/LandIce_Gather2DField_Def.hpp
  src/landIce/evaluators/LandIce_GatherVerticallyContractedSolution_Def.hpp
  src/landIce/evaluators/LandIce_ResponseGLFlux_Def.hpp
  src/landIce/evaluators/LandIce_ResponseSMBMismatch_Def.hpp
  src/landIce/evaluators/LandIce_ScatterResidual2D_Def.hpp
  tests/landIce/FO_GIS/input_fo_gis_coupled.yaml
  tests/landIce/FO_GIS/input_fo_gis_coupledT.yaml
Labels: enhancement, bugfix
