Repository sandialabs/Albany, pull requests merged in 2024-09, with the labels that each got.

#1057 Add transient optimization problems
  src/Main_Analysis.cpp
  tests/corePDEs/TransientHeat2D/CMakeLists.txt
  tests/corePDEs/TransientHeat2D/performGradientChecks.py
  tests/corePDEs/TransientHeat2D/tempus_be_nox_analysis_integrated_response_distributed_param.yaml
  tests/corePDEs/TransientHeat2D/tempus_be_nox_analysis_integrated_response_scalar_params.yaml
  tests/corePDEs/TransientHeat2D/tempus_be_nox_analysis_rol_driven_scalar_params.yaml
  tests/corePDEs/TransientHeat2D/tempus_be_nox_analysis_rol_driven_scalar_params_2.yaml
  tests/corePDEs/TransientHeat2D/tempus_be_nox_analysis_tempus_driven_scalar_params.yaml
  tests/corePDEs/TransientHeat2D/tempus_be_nox_analysis_tempus_driven_scalar_params_2.yaml
Labels: enhancement

#1075 Fix compilation error
  src/Albany_StateManager.cpp
  tests/CMakeLists.txt
Labels: Trilinos, bugfix

#1082 STK-related fixes to let Albany build correctly
  src/disc/stk/Albany_STKDiscretization.cpp
  src/disc/stk/Albany_STKFieldContainerHelper.cpp
  src/disc/stk/Albany_STKUtils.hpp
Labels: STK, bugfix
